---
  - name: Install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
    become: true
    

  - name: Set nginx.conf on webservers
    copy:
      src: "{{ conf_file }}.conf"
      dest: "{{ dest_path }}"
    become: true
    
    notify:
      - Restart nginx
    
