---
- hosts: webservers:loadbalancers
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      become: true

- name: Configure webservers
  hosts: webservers
  roles:
    - set_web

- name: Configure loadbalancers
  hosts: loadbalancers
  roles: 
    - set_loadbalancer