filebeat.config:
  process:
    username: root
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: docker
  containers:
    ids:
      - "*"
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - drop_event:
        when:
          not:
            equals:
              container.name: "filebeat"      
- type: log
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  paths:
    - /logs_to_parse/*.log

# output.file:
#   filename: logs.log
#   path: /var/lib/filebeat/logs
output.logstash:
  hosts: ["${LOGSTASH_HOST}"]

