---
  - name: Install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
    become: true
    
  - name: Set serv as proxy
    copy:
      src: "loadbalancer.conf"
      dest: "{{ dest_path }}"
    become: true
    
    notify:
      - Restart nginx
    
