---
- name: install prerequisites
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: add apt-key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: install docker
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io
    update_cache: yes
    
- name: Add {{ ansible_user }} to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install docker-compose
  become: true
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64'
    dest: /usr/local/bin/docker-compose
    mode: '+x'
  retries: 10
  delay: 2
